[build]
  publish = "."
  command = "npm run build"

[[redirects]]
  from = "/staff/*"
  to = "/staff/pages/:splat"
  status = 200

[[redirects]]
  from = "/students/*"
  to = "/students/pages/:splat" 
  status = 200

[[redirects]]
  from = "/*"
  to = "/staff/pages/login.html"
  status = 200